### ISSUE TITLE
Not able to create POJO

### ISSUE THREAD

**Issue by dbclkclk** [mtedone/podam#109]
Trying to create a POJO of a Spring Oauth Security Object shows this error:

     08:37:58.972 [main] DEBUG u.c.jemos.podam.api.PodamFactoryImpl - We couldn't create an   instance for pojo: class org.springframework.security.oauth2.provider.OAuth2Authentication with  constructor: public    org.springframework.security.oauth2.provider.OAuth2Authentication(org.springframework.security.o auth2.provider.OAuth2Request,org.springframework.security.core.Authentication). Will try with  another one.
      java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at   uk.co.jemos.podam.api.PodamFactoryImpl.populatePojoInternal(PodamFactoryImpl.java:1397)   [podam-5.4.1.RELEASE.jar:na]
	at   uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoInternal(PodamFactoryImpl.java:1239)   [podam-5.4.1.RELEASE.jar:na]
	at   uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoInternal(PodamFactoryImpl.java:1197)   [podam-5.4.1.RELEASE.jar:na]
	at   uk.co.jemos.podam.api.PodamFactoryImpl.manufactureAttributeValue(PodamFactoryImpl.java:1635) [podam-5.4.1.RELEASE.jar:na]
	at   uk.co.jemos.podam.api.PodamFactoryImpl.manufactureParameterValue(PodamFactoryImpl.java:30 59) [podam-5.4.1.RELEASE.jar:na]
	at   uk.co.jemos.podam.api.PodamFactoryImpl.getParameterValuesForConstructor(PodamFactoryImpl.java:2829) [podam-5.4.1.RELEASE.jar:na]
	at uk.co.jemos.podam.api.PodamFactoryImpl.instantiatePojo(PodamFactoryImpl.java:1092)   [podam-5.4.1.RELEASE.jar:na]
	at    uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoInternal(PodamFactoryImpl.java:1212)   [podam-5.4.1.RELEASE.jar:na]
	at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojo(PodamFactoryImpl.java:170)    [podam-5.4.1.RELEASE.jar:na]
	at   com.cointraders.api.services.CustomTokenStoreServiceUnitTest.testReadAuthenticationThatItReturnsOAuth2Authentication(CustomTokenStoreServiceUnitTest.java:73) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)   [junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)   [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160) [junit-4.11.jar:na]
	at   com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)   [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68) [junit-rt.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~ [na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
     Caused by: java.lang.IllegalArgumentException: Once created you cannot set this token to   authenticated. Create a new instance using the constructor which takes a GrantedAuthority list will   mark this as authenticated.
	at   org.springframework.security.authentication.UsernamePasswordAuthenticationToken.setAuthenticated(UsernamePasswordAuthenticationToken.java:87) ~[spring-security-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	... 41 common frames omitted
      08:37:59.162 [main] DEBUG u.c.jemos.podam.api.PodamFactoryImpl - For class class org.springframework.security.oauth2.provider.OAuth2Authentication PODAM could not possibly   create a value. Will try other means.
      08:37:59.165 [main] WARN  u.c.jemos.podam.api.PodamFactoryImpl - Failed to manufacture class  org.springframework.security.oauth2.provider.OAuth2Authentication. Resorting to   uk.co.jemos.podam.api.NullExternalFactory external factory
      08:37:59.167 [main] WARN  u.c.j.podam.api.NullExternalFactory - Cannot instantiate class  org.springframework.security.oauth2.provider.OAuth2Authentication with arguments []. Returning null.

The Spring Oauth2 library version I'm using is 2.0.7.RELEASE

My actual test:

      @Test
      public void testReadAuthenticationThatItReturnsOAuth2Authentication()
     {

        PodamFactory factory = new PodamFactoryImpl();
        DefaultOAuth2AccessToken oAuth2AccessToken = factory.manufacturePojo(DefaultOAuth2AccessToken.class);

        ((RandomDataProviderStrategy)factory.getStrategy()).addSpecific(OAuth2RefreshToken.class, DefaultOAuth2RefreshToken.class);
        ((RandomDataProviderStrategy)factory.getStrategy()).addSpecific(Authentication.class, UsernamePasswordAuthenticationToken.class);
          ((RandomDataProviderStrategy)factory.getStrategy()).addSpecific(GrantedAuthority.class,SimpleGrantedAuthority.class);

        OauthAccessToken oauthAccessToken = factory.manufacturePojo((OauthAccessToken.class));

        OAuth2Authentication oAuth2Authentication = factory.manufacturePojo(OAuth2Authentication.class);

        byte[] byteOauth2Authentication = SerializationUtils.serialize(oAuth2Authentication);

        oauthAccessToken.setAuthentication(byteOauth2Authentication);

        Mockito.when(this.mockOauthAccessTokenRepository.findOne(Mockito.any(Specification.class))).thenReturn(oauthAccessToken);

        OAuth2Authentication result = this.customTokenStoreServiceImpl.readAuthentication(oAuth2AccessToken);

        Assert.assertNotNull(result);

       }

**Comment by mtedone** [comment]
@Test
    public void testPojoManufacturing() throws Exception {

        PodamFactory factory = new PodamFactoryImpl(new MyExternalOAuthFactory());

        DefaultOAuth2AccessToken pojo = factory.manufacturePojo(DefaultOAuth2AccessToken.class);
        Assert.assertNotNull(pojo);


    }



    private static final class MyExternalOAuthFactory extends AbstractExternalFactory {


        @Override
        public <T> T manufacturePojo(Class<T> pojoClass, Type... genericTypeArgs) {

            if (pojoClass.isAssignableFrom(DefaultOAuth2AccessToken.class)) {
                return (T) new DefaultOAuth2AccessToken((String)null);
            }

            return null;

        }


        @Override
        public <T> T populatePojo(T pojo, Type... genericTypeArgs) {
            return null;
        }
    }

**Comment by dbclkclk** [comment]
@mtedone looking at the code, it seems it needs a certain boolean value to be passed to **UsernamePasswordAuthenticationToken.setAuthenticated** method. This is a setter that accepts a boolean but, the parameter should always accept `true`.  Is there an adapter for setters? It seems **AbstractExternalFactory** only works for constructors.

**Comment by mtedone** [comment]
You can use AttributeMetadata to customise your value. Please refer to the documentation on the website: http://mtedone.github.io/podam/ In the section titled: 

"Define custom DataProviderStrategy, which will be producing values depending on attribute type"

Basically: 

```
public class CustomProviderStrategy extends AbstractRandomDataProviderStrategy {

        @Override
        public String getStringValue(AttributeMetadata attributeMetadata) {

                if (Pojo.class.isAssignableFrom(attributeMetadata.getPojoClass())) {

                        if ("url".equals(attributeMetadata.getAttributeName())) {
                                return "http://wikipedia.org";
                        } else if ("postCode".equals(attributeMetadata.getAttributeName())) {
                                return "00100";
                        }
                }
                return super.getStringValue(attributeMetadata);
        }
}
```
