### ISSUE TITLE
Excpetion filling com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl Pojo

### ISSUE THREAD

**Issue by mancioshell** [mtedone/podam#113]
Hello! I'm using 5.5.1.RELEASE Podam version. 
I'm tryng to do this:
```
RandomDataProviderStrategy strategy = new RandomDataProviderStrategyImpl();
strategy.addOrReplaceSpecific(XMLGregorianCalendar.class, XMLGregorianCalendarImpl.class);
    	
PodamFactory factory = new PodamFactoryImpl(strategy);
XMLGregorianCalendar pojo = factory.manufacturePojo(XMLGregorianCalendar.class);
```

where XMLGregorianCalendarImpl is com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl.
My code throws an Exception:
```
Exception in thread "main" uk.co.jemos.podam.exceptions.PodamMockeryException
	at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojo(PodamFactoryImpl.java:182)
	at it.sogei.podam.App.main(App.java:35)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at uk.co.jemos.podam.api.PodamFactoryImpl.populatePojoInternal(PodamFactoryImpl.java:1407)
	at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoInternal(PodamFactoryImpl.java:1249)
	at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoInternal(PodamFactoryImpl.java:1234)
	at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojo(PodamFactoryImpl.java:175)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Valore -247.795.888 non valido per il campo Day.
	at com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl.invalidFieldValue(XMLGregorianCalendarImpl.java:1294)
	at com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl.setDay(XMLGregorianCalendarImpl.java:1250)
	... 9 more
```

How can i fix this? 

Thanks in advance. Best regards,
Alessandro.

**Comment by mancioshell** [comment]
Hi found the answer!
Maybe this help someone with my same problem:

```
import java.lang.reflect.Type;
import java.util.GregorianCalendar;

import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import uk.co.jemos.podam.api.PodamFactoryImpl;

public class XMLGregorianCalendarExternalFactory extends PodamFactoryImpl {

	@SuppressWarnings("unchecked")
	public <T> T manufacturePojo(Class<T> pojoClass, Type... genericTypeArgs) {
		// TODO Auto-generated method stub
		if(pojoClass.isAssignableFrom(XMLGregorianCalendar.class)){
			
			XMLGregorianCalendar now = null;
			try {
				GregorianCalendar gregorianCalendar = new GregorianCalendar();
		        DatatypeFactory datatypeFactory = DatatypeFactory.newInstance();
		        now = datatypeFactory.newXMLGregorianCalendar(gregorianCalendar);
			} catch (DatatypeConfigurationException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}			
			return (T) now;
		}else{
			return super.manufacturePojoWithFullData(pojoClass, genericTypeArgs);
		}
				
	}

	public <T> T populatePojo(T pojo, Type... genericTypeArgs) {
		// TODO Auto-generated method stub
		return super.populatePojo(pojo, genericTypeArgs);		
	}
}
```

**Comment by mtedone** [comment]
Try using an external factory as documented on the website.
